name: retrofit_demo
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  retrofit: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator:
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


